# Site settings
title: Abhishek Gupta - Product+UX Designer
email: abhishekgupta.t@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An experienced designer with entrepreneurial spirit. Worked with Truecaller and studied at IIT Roorkee.
baseurl:  # the subpath of your site, e.g. /blog/
url:  "localhost:4000"
twitter_username: abhishekgpta
github_username:  abhishekguptat

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"
